using System;

namespace SpaceWars.Core;

/// <summary>
/// NASA Standard Breakup Model (Johnson, Krisko, Liou, Anz-Meador, 2001 — "NASA's new
/// breakup model of EVOLVE 4.0"), collision branch. Produces the size distribution of
/// fragments generated by a collision, which is the seed of any Kessler cascade.
///
/// Cumulative count of fragments with characteristic length ≥ Lc:
///     N(&gt;Lc) = 0.1 · M_eff^0.75 · Lc^(-1.71)     (Lc in metres, M_eff in kg)
///
/// where the "effective mass" M_eff depends on whether the collision is catastrophic.
/// The exponents are empirical fits to hypervelocity impact tests and on-orbit events.
/// </summary>
public static class BreakupModel
{
    private const double SizeCoefficient = 0.1;
    private const double SizeMassExponent = 0.75;
    private const double SizeLengthExponent = -1.71;

    /// <summary>Standard reference sizes [m]: 1 mm, 1 cm, 10 cm (trackable), 1 m.</summary>
    public static readonly double[] ReferenceSizesMeters = [0.001, 0.01, 0.10, 1.0];

    /// <summary>
    /// Effective mass [kg] fed into the size-distribution law.
    /// Catastrophic: sum of both masses. Non-catastrophic: projectile mass scaled by the
    /// square of the impact speed in km/s (the model's empirical cratering-mass proxy).
    /// </summary>
    public static double EffectiveMass(double targetMassKg, double projectileMassKg, double relVelMetersPerSec)
    {
        if (Lethality.IsCatastrophic(projectileMassKg, relVelMetersPerSec, targetMassKg))
            return targetMassKg + projectileMassKg;

        double vKmS = relVelMetersPerSec / 1000.0;
        return projectileMassKg * vKmS * vKmS;
    }

    /// <summary>Cumulative number of fragments with characteristic length ≥ <paramref name="lcMeters"/>.</summary>
    public static double CountLargerThan(double effectiveMassKg, double lcMeters)
        => SizeCoefficient * Math.Pow(effectiveMassKg, SizeMassExponent)
                           * Math.Pow(lcMeters, SizeLengthExponent);

    /// <summary>
    /// Full description of a single fragmentation event: catastrophic flag, effective
    /// mass, and fragment counts at the standard reference sizes.
    /// </summary>
    public static FragmentationResult Fragment(double targetMassKg, double projectileMassKg, double relVelMetersPerSec)
    {
        bool catastrophic = Lethality.IsCatastrophic(projectileMassKg, relVelMetersPerSec, targetMassKg);
        double mEff = EffectiveMass(targetMassKg, projectileMassKg, relVelMetersPerSec);

        return new FragmentationResult
        {
            Catastrophic = catastrophic,
            EmrJoulesPerGram = Lethality.Emr(projectileMassKg, relVelMetersPerSec, targetMassKg),
            EffectiveMassKg = mEff,
            CountLargerThan1mm = CountLargerThan(mEff, 0.001),
            CountLargerThan1cm = CountLargerThan(mEff, 0.01),
            CountLargerThan10cm = CountLargerThan(mEff, 0.10),
        };
    }
}

public struct FragmentationResult
{
    public bool Catastrophic;
    public double EmrJoulesPerGram;
    public double EffectiveMassKg;
    /// <summary>Total fragment count ≥ 1 mm (dominates the untrackable lethal population).</summary>
    public double CountLargerThan1mm;
    /// <summary>Fragment count ≥ 1 cm (the lethal-but-untrackable class).</summary>
    public double CountLargerThan1cm;
    /// <summary>Fragment count ≥ 10 cm (roughly the trackable / catalogued class).</summary>
    public double CountLargerThan10cm;

    public override readonly string ToString()
        => $"{(Catastrophic ? "CATASTROPHIC" : "non-catastrophic")} " +
           $"EMR={EmrJoulesPerGram:F0} J/g, Meff={EffectiveMassKg:F1} kg → " +
           $"{CountLargerThan1cm:N0} frags >1cm, {CountLargerThan10cm:N0} >10cm";
}
